dnnlib: Running run_generator.generate_images() on localhost...
Il problema è il caricamento del decoder
Il problema è la scelta del device
Using device: cuda:0
Using device: cpu
Traceback (most recent call last):
  File "/home/giacomo/.pyenv/versions/stylegan2/lib/python3.7/site-packages/torch/serialization.py", line 348, in _check_seekable
    f.seek(f.tell())
AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_generator.py", line 226, in <module>
    main()
  File "run_generator.py", line 221, in main
    dnnlib.submit_run(sc, func_name_map[subcmd], **kwargs)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/run_generator.py", line 45, in generate_images
    state_dict = torch.load(decoder_path, map_location=device)
  File "/home/giacomo/.pyenv/versions/stylegan2/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/giacomo/.pyenv/versions/stylegan2/lib/python3.7/site-packages/torch/serialization.py", line 275, in _open_file_like
    return _open_buffer_reader(name_or_buffer)
  File "/home/giacomo/.pyenv/versions/stylegan2/lib/python3.7/site-packages/torch/serialization.py", line 260, in __init__
    _check_seekable(buffer)
  File "/home/giacomo/.pyenv/versions/stylegan2/lib/python3.7/site-packages/torch/serialization.py", line 351, in _check_seekable
    raise_err_msg(["seek", "tell"], e)
  File "/home/giacomo/.pyenv/versions/stylegan2/lib/python3.7/site-packages/torch/serialization.py", line 344, in raise_err_msg
    raise type(e)(msg)
AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.
