dnnlib: Running run_generator.generate_images() on localhost...
Loading networks from "/media/giacomo/hdd_ubuntu/Downloads/stylegan2_pretrained_celeba.pkl"...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Preprocessing... Loading... Done.
generating
Traceback (most recent call last):
  File "run_generator.py", line 195, in <module>
    main()
  File "run_generator.py", line 190, in main
    dnnlib.submit_run(sc, func_name_map[subcmd], **kwargs)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/run_generator.py", line 59, in generate_images
    PIL.Image.fromarray(images[0], 'RGB').save(dnnlib.make_run_dir_path(seed))
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/submit.py", line 189, in make_run_dir_path
    return os.path.join(dnnlib.submit_config.run_dir, *paths)
  File "/home/giacomo/.pyenv/versions/3.7.17/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/giacomo/.pyenv/versions/3.7.17/lib/python3.7/genericpath.py", line 153, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'
