dnnlib: Running run_generator.generate_images() on localhost...
Loading networks from "/media/giacomo/hdd_ubuntu/Downloads/stylegan2_pretrained_celeba.pkl"...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Loading... Done.
Setting up TensorFlow plugin "upfirdn_2d.cu": Preprocessing... Loading... Done.
Traceback (most recent call last):
  File "run_generator.py", line 195, in <module>
    main()
  File "run_generator.py", line 190, in main
    dnnlib.submit_run(sc, func_name_map[subcmd], **kwargs)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/run_generator.py", line 44, in generate_images
    _G, _D, Gs = pretrained_networks.load_networks(network_pkl)
  File "/home/giacomo/Desktop/codice 19-08/stylegan2_mio/pretrained_networks.py", line 76, in load_networks
    G, D, Gs = pickle.load(stream, encoding='latin1')
ValueError: too many values to unpack (expected 3)
