dnnlib: Running run_generator.generate_images() on localhost...
Il problema è il caricamento del decoder
Il problema è la scelta del device
Using device: cuda:0
Using device: cpu
Loading networks from "/media/giacomo/hdd_ubuntu/Downloads/stylegan2_pretrained_celeba.pkl"...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... Failed!
Traceback (most recent call last):
  File "run_generator.py", line 221, in <module>
    main()
  File "run_generator.py", line 216, in main
    dnnlib.submit_run(sc, func_name_map[subcmd], **kwargs)
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/submission/submit.py", line 343, in submit_run
    return farm.submit(submit_config, host_run_dir)
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/submission/internal/local.py", line 22, in submit
    return run_wrapper(submit_config)
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/submission/submit.py", line 280, in run_wrapper
    run_func_obj(**submit_config.run_func_kwargs)
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/run_generator.py", line 60, in generate_images
    data = pickle.load(f)
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/tflib/network.py", line 297, in __setstate__
    self._init_graph()
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/tflib/network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 491, in G_synthesis_stylegan2
  File "<string>", line 455, in layer
  File "<string>", line 99, in modulated_conv2d_layer
  File "<string>", line 68, in apply_bias_act
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/tflib/ops/fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/tflib/ops/fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/tflib/ops/fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/tflib/custom_ops.py", line 130, in get_plugin
    compile_opts += ' --gpu-architecture=%s' % _get_cuda_gpu_arch_string()
  File "/media/giacomo/hdd_ubuntu/codice 25-08/stylegan2_mio/dnnlib/tflib/custom_ops.py", line 52, in _get_cuda_gpu_arch_string
    raise RuntimeError('No GPU devices found')
RuntimeError: No GPU devices found
